module.exports = {
  backgroundColors: require("./background-colors"),
  borderColors: require("./border-colors"),
  borderRadius: require("./border-radius"),
  borderWidths: require("./border-widths"),
  margins: require("./margins"),
  paddings: require("./paddings"),
  heights: require("./heights"),
  widths: require("./widths"),
  flex: require("./flex"),
  fontSizes: require("./font-sizes"),
  textColors: require("./text-colors"),
  textAlignments: require("./text-alignments"),
  fontWeights: require("./font-weights"),
  fontFamilies: require("./font-families"),
  zIndexes: require("./z-indexes"),
  opacities: require("./opacities"),
  positions: require("./positions"),
  insets: require("./insets"),
  boxShadows: require("./box-shadows"),
  lineHeights: require("./line-heights"),
};
